version: '3.8'

services:
  # Main FitBite application
  fitbite-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitbite-app
    restart: unless-stopped
    ports:
      - "3001:5000"  # Expose on port 3001 to avoid conflicts
    environment:
      - NODE_ENV=production
      - PORT=5000
      # These will be set via .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./logs:/app/logs
      - ./server/temp:/app/server/temp
    networks:
      - fitbite-network
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fitbite.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.fitbite.loadbalancer.server.port=5000"

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: fitbite-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fitbite-network
    command: redis-server --appendonly yes

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: fitbite-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - fitbite-network
    depends_on:
      - fitbite-app

  # PostgreSQL database (optional - use if not using external DB)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: fitbite-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: fitbite
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - fitbite-network

networks:
  fitbite-network:
    driver: bridge

volumes:
  redis-data:
  # postgres-data:  # Uncomment if using local PostgreSQL